### ISSUE TITLE
uccp420wifi stack trace failure potentially due to continuous association and dissociation with AP

### ISSUE THREAD

**Issue by nikhil-zinjurde-imgtec** [CreatorDev/uccp420wlan#17]
[uccp420_failure_log.txt](https://github.com/CreatorDev/uccp420wlan/files/787096/uccp420_failure_log.txt)

The above attached dmesg logs show a stack trace failure number of times, when the Ci40 board keeps trying to reconnect with the associated AP to its wlan0 interface.  **Note that this board also had a softAP interface wlan0-1 interface up.**

After this failure, the interface did not have ipv4 address associated to it, also scanning for wireless networks from LuCI failed to list any networks.

**Comment by tkc17** [comment]
Hi Nikhil,

Thanks for reporting the problem.  

From the logs i could see 

a) We are constantly losing connection to AP, this might be expected if you are rebooting the AP? Can you please confirm that.

b) After a while, looks like RPU locked up, hence the driver times out for many CMD's and prints a kernel warning.

Please confirm/provide the below details?

1. wlan0-STA interface is connecting with AP on channel 8 (2452 MHz), 20 MHz  
2. Is the wlan0-1 AP interface also operating at channel 8-20MHz.
3. After the issue, can you please run the command "sh get_rpu_stat.sh" and share the stats file?

**Comment by nikhil-zinjurde-imgtec** [comment]
Hi @chaitu-tk 

> a) We are constantly losing connection to AP, this might be expected if you are rebooting the AP? Can you please confirm that.

Actually, this is the common company wireless AP to connect personal devices, we face frequent issues of connections with this particular router/AP.  It is not being manually rebooted.  I was using this AP to reproduce an issue for @tjobanpu where the wlan0 interface was not getting an ipv4 address with the company wireless AP.

> 1. wlan0-STA interface is connecting with AP on channel 8 (2452 MHz), 20 MHz
> 2. Is the wlan0-1 AP interface also operating at channel 8-20MHz.

I see now that both the interfaces are connected to the same channel i.e. 9

    root@OpenWrt:/# iw dev
    phy#0
            Interface wlan0-1
                    ifindex 7
                    wdev 0x3
                    addr 00:19:f5:89:02:9e
                    ssid testimagi
                    type AP
                    channel 9 (2452 MHz), width: 20 MHz, center1: 2452 MHz
                    txpower 20.00 dBm
            Interface wlan0
                    ifindex 6
                    wdev 0x2
                    addr 00:19:f5:89:02:9d
                    type managed
                    channel 9 (2452 MHz), width: 20 MHz, center1: 2452 MHz
                    txpower 20.00 dBm

> 3. After the issue, can you please run the command "sh get_rpu_stat.sh" and share the stats file?

Yes, sure.  I have set up the board for soak test again.  If and when the failure occurs, I will check and share.

**Comment by tkc17** [comment]
> Actually, this is the common company wireless AP to connect personal devices, we face frequent issues of connections with this particular router/AP. It is not being manually rebooted. I was using this AP to reproduce an issue for @tjobanpu where the wlan0 interface was not getting an ipv4 address with the company wireless AP

Ok i understand. But as per @tjobanpu report we should see disconnections due to INACTIVITY, but in this case we are seeing "Connection to AP lost", so first we need to understand this disconnections. Can you find out the mode and FW version of the AP, if we have it locally we will run the same test.

>I see now that both the interfaces are connected to the same channel i.e. 9
root@OpenWrt:/# iw dev
phy#0
        Interface wlan0-1
                ifindex 7
                wdev 0x3
                addr 00:19:f5:89:02:9e
                ssid testimagi
                type AP
                channel 9 (2452 MHz), width: 20 MHz, center1: 2452 MHz
                txpower 20.00 dBm
        Interface wlan0
                ifindex 6
                wdev 0x2
                addr 00:19:f5:89:02:9d
                type managed
                channel 9 (2452 MHz), width: 20 MHz, center1: 2452 MHz
                txpower 20.00 dBm

Sorry channel 9 is correct.

>Yes, sure. I have set up the board for soak test again. If and when the failure occurs, I will check and share.

That would be helpful. Can you try connecting to the AP manually and see if our DUT disconnects? My approach would be

a) Try Manually and understand the reason for disconnections
b) Try Soak Test to repro the RPU lockup which is causing kernel warnings.

**Comment by tjobanpu** [comment]
I cant help noticing that the disconnection happens during ampdu_action() function, and it happens within 30 seconds of association, this leads me to believe that the problem could lie in the block ack negotiation. Probably an airtrace could help us understand the issue.

**Comment by tkc17** [comment]
>I cant help noticing that the disconnection happens during ampdu_action() function, and it happens within 30 seconds of association, this leads me to believe that the problem could lie in the block ack negotiation. Probably an airtrace could help us understand the issue.

Yes, a sniffer trace would be very valuable.

**Comment by nikhil-zinjurde-imgtec** [comment]
I can confirm that the repeated disconnection is due to AP misbehavior. The AP in test is known to be prone of losing connection to devices. Have tested with other wireless APs, found no problems of disconnection with Ci40 board
