### ISSUE TITLE
DFS in 11ac not working

### ISSUE THREAD

**Issue by Shpinkso** [CreatorDev/uccp420wlan#5]

**Comment by tjobanpu** [comment]
Procedure:
From Luci Network->wireless->Edit->AC if channel number exceeding 48 is selected the hostapd crashes and from the logs it seems that DFS malfunctioned.  The DFS implementation in the driver needs to be properly investigated.

Hostapd Logs:

Configuration file: /var/run/hostapd-phy0.conf
[  209.264740] img/uccp420wlan/MCP_LOADER.ldr is loaded
[  209.326394] img/uccp420wlan/MAC_LOADER.ldr is loaded
[  210.912262] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
wlan0: interface state COUNTRY_UPDATE->DFS
wlan0: DFS-CAC-START freq=5280 chan=56 sec_chan=0, width=0, seg0=0, seg1=0, cac_time=60s
DFS start_dfs_cac() failed, -1
Interface initialization failed
wlan0: interface state DFS->DISABLED
wlan0: AP-DISABLED 
wlan0: Unable to setup interface.
wlan0: interface state DISABLED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
ELOOP: remaining socket: sock=12 eloop_data=0x77413760 user_data=0 handler=0x42c068

**Comment by tkc17** [comment]
Hi, 

If you check the interface combinations DFS in AP is not supported yet. use "iw phy" and look for "valid interface combinations:", if you see "radar detect widths" against the interface type then DFS is supported for that interface.

Currently only STA mode supports DFS.
